#!/bin/bash

# brew install marp-cli

marp onsg.md --theme-set themes/tombola.css --theme tombola --html
marp bdha.md --theme-set themes/tombola.css --theme tombola --html
marp index.md --theme-set themes/tombola.css --theme tombola -w --html
